# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

jobs:
- job: Build
  timeoutInMinutes: 360

  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-16.04'
        CXX: '/usr/bin/clang++'
        CC: '/usr/bin/clang'
        buildPlatform: 'linux'
      mac:
        imageName: 'macos-10.13'
        DEVELOPER_DIR: '/Applications/Xcode_9.4.1.app'
        buildPlatform: 'osx'

      windows:
        imageName: 'vs2017-win2016'
        buildPlatform: 'windows'

  variables:
    VCPKG_ROOT: '$(Build.SourcesDirectory)/vcpkg'
    archiveFile: '$(Build.ArtifactStagingDirectory)/flimfit-env-$(buildPlatform).zip'

  pool:
    vmImage: $(imageName)

  steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
      
    - script: brew install gcc6 p7zip
      displayName: 'Install brew dependencies'
      condition: eq(variables['buildPlatform'],'osx')

    - task: CopyFiles@2
      inputs:
        contents: '**'
        targetFolder: '$(Build.SourcesDirectory)/vcpkg'

    - script: python build-flimfit-env.py
      workingDirectory: 'vcpkg'
      displayName: 'Build vcpkg ports'

    - task: CopyFiles@2
      condition: always() 
      inputs:
        contents: 'vcpkg/buildtrees/**/*.log'
        targetFolder: '$(Build.ArtifactStagingDirectory)/logs'

    - task: PublishBuildArtifacts@1
      condition: always() 
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/logs'
        artifactName: 'vcpkg-logs-$(buildPlatform)'
      
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/vcpkg'
        archiveType: 'zip'
        archiveFile: '$(archiveFile)'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(archiveFile)'
        artifactName: 'flimfit-env-$(buildPlatform)'