# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

jobs:
- job: Build
  timeoutInMinutes: 360

  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-16.04'
        CXX: '/usr/bin/clang++'
        CC: '/usr/bin/clang'
        buildPlatform: 'linux'
        setupCommand: 'sudo apt-get install libfontconfig1-dev libfreetype6-dev libx11-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libx11-xcb-dev libxcb-glx0-dev libxkbcommon-dev'
      mac:
        imageName: 'macos-10.13'
        DEVELOPER_DIR: '/Applications/Xcode_10.1.app'
        buildPlatform: 'osx'
        setupCommand: brew install gcc6 p7zip

      windows:
        imageName: 'vs2017-win2016'
        buildPlatform: 'windows'
        setupCommand: ''

  variables:
    VCPKG_ROOT: '$(Build.SourcesDirectory)/vcpkg'
    archiveFile: '$(Build.ArtifactStagingDirectory)/flimfit-env-$(buildPlatform).zip'

  pool:
    vmImage: $(imageName)

  steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
      
    - script: $(setupCommand)
      displayName: 'Install dependencies'

    - task: CopyFiles@2
      inputs:
        contents: '**'
        targetFolder: '$(Build.SourcesDirectory)/vcpkg'

    - script: python build-flimfit-env.py
      workingDirectory: 'vcpkg'
      displayName: 'Build vcpkg ports'

    - task: CopyFiles@2
      condition: always() 
      inputs:
        contents: 'vcpkg/buildtrees/**/*.log'
        targetFolder: '$(Build.ArtifactStagingDirectory)/logs'

    - task: PublishBuildArtifacts@1
      condition: always() 
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/logs'
        artifactName: 'vcpkg-logs-$(buildPlatform)'
      
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/vcpkg'
        archiveType: 'zip'
        archiveFile: '$(archiveFile)'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(archiveFile)'
        artifactName: 'flimfit-env-$(buildPlatform)'
    
    - task: TriggerPipeline@1
      condition: eq(variables['buildPlatform'], 'windows')
      inputs:
        serviceConnection: 'azure-devops'
        project: '6439e790-bc20-4600-8a79-6e11fc8b08c2'
        Pipeline: 'Build'
        buildDefinition: 'Galene'